spring:
  application:
    name: DiscoveryServer
  cloud:
    eureka:
      client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: false
    refresh:
      enable: true