spring:
  application:
    name: APIGateWay
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
